[package]
name = "cw721-spaceship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cw-multi-test = "0.13.2"

cw721 = "0.13.2"
cw721-base = { version = "0.13.2", features = ["library"] }

cosmonaut-cw20 = {path= "../../contracts/cosmonaut-cw20", features=["library"]}
cosmonaut-cw721 = {path= "../../contracts/cosmonaut-cw721", features=["library"]}
cosmonaut-main = {path="../../contracts/cosmonaut-main", features=["library"]}

base = {path="../base"}


