[package]
name = "base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_json = "1.0.81"
schemars = "0.8.10"
cosmwasm-std = { version = "1.0.0" }
anyhow = { version = "1.0.57", features = ["backtrace"] }
cw-multi-test = "0.13.2"
