[package]
name = "base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0" }
serde = { version = "1.0.137", default-features = false, features = ["derive"] }

cw-multi-test = "0.13.2"
