[package]
name = "cw20-tokens"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0" }

cosmonaut-cw20 = {path= "../../contracts/cosmonaut-cw20", features=["library"]}
cosmonaut-cw721 = {path= "../../contracts/cosmonaut-cw721", features=["library"]}
cosmonaut-main = {path="../../contracts/cosmonaut-main", features=["library"]}
cw20 = "0.13.4"
base = {path="../base"}

cw-multi-test = "0.13.2"
